### ISSUE TITLE
Style elements within text editors using the `atom-text-editor::shadow` selector or the `.atom-text-editor.less` file extension.If you want to target overlay elements, target them directly or as descendants of `atom-overlay` elements.

### ISSUE THREAD

**Issue by nicolasmccurdy** [atom/editor-stats#16]
In styles/editor-stats.less: Style elements within text editors using the `atom-text-editor::shadow` selector or the `.atom-text-editor.less` file extension.
If you want to target overlay elements, target them directly or as descendants of `atom-overlay` elements.

**Comment by kevinsawicki** [comment]
This is a false positive, see https://github.com/atom/atom-selector-linter/issues/1 for more details

**Comment by nicolasmccurdy** [comment]
Thanks for the quick response!
