### ISSUE TITLE
How do I turn this on by default?

### ISSUE THREAD

**Issue by erebor** [atom/editor-stats#22]
I used to have this in my init.coffee file:

```
atom.workspaceView.trigger 'editor-stats:toggle'
```

It worked great, but now that `workspaceView` is deprecated and stuff, it fails. So how do I do it now?

**Comment by kevinsawicki** [comment]
I think this:

```coffee
atom.commands.dispatch(atom.views.getView(atom.workspace), 'editor-stats:toggle')
```

**Comment by erebor** [comment]
That did it! Thanks very much. I wonder if this is a common enough desire to make it up to the README?

Thanks either way!  I need my little stats bar.
